from enum import StrEnum


class TrustStatus(StrEnum):
    TRUSTED_LIVE = "TRUSTED_LIVE"
    SUSPECT_DEVICE_TIME = "SUSPECT_DEVICE_TIME"
    SUSPECT_DEVICE_CLOCK_JUMP = "SUSPECT_DEVICE_CLOCK_JUMP"
    SUSPECT_PC_TIME = "SUSPECT_PC_TIME"
    INTERNET_OFFLINE_TRUSTED_LOCAL = "INTERNET_OFFLINE_TRUSTED_LOCAL"
    LAN_DEVICE_OFFLINE = "LAN_DEVICE_OFFLINE"
    BACKFILL_ACCEPTED_CLOCK_OK = "BACKFILL_ACCEPTED_CLOCK_OK"
    BACKFILL_UNVERIFIED_BLIND_PERIOD = "BACKFILL_UNVERIFIED_BLIND_PERIOD"
    BACKFILL_SUSPECT_TIME = "BACKFILL_SUSPECT_TIME"
    BACKFILL_UNVERIFIED_AGENT_DOWN = "BACKFILL_UNVERIFIED_AGENT_DOWN"
    DUMP_RECONCILE_NORMAL = "DUMP_RECONCILE_NORMAL"
    DUPLICATE = "DUPLICATE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    SUSPECT_MISSING_CLOCK_CHECK = "SUSPECT_MISSING_CLOCK_CHECK"


class SourceType(StrEnum):
    LIVE = "LIVE"
    DUMP_RECONNECT = "DUMP_RECONNECT"
    DUMP_STARTUP = "DUMP_STARTUP"
    MANUAL_REPROCESS = "MANUAL_REPROCESS"


class SyncStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    ACKED = "ACKED"
    FAILED = "FAILED"


class ClockStatus(StrEnum):
    OK = "OK"
    SUSPICIOUS = "SUSPICIOUS"
    ERROR = "ERROR"


class OutageType(StrEnum):
    INTERNET_OUTAGE = "INTERNET_OUTAGE"
    DEVICE_LAN_OUTAGE = "DEVICE_LAN_OUTAGE"
    ZONE_AGENT_DOWN = "ZONE_AGENT_DOWN"
    PC_REBOOT = "PC_REBOOT"


class IncidentType(StrEnum):
    DEVICE_CLOCK_DRIFT = "DEVICE_CLOCK_DRIFT"
    DEVICE_CLOCK_JUMP = "DEVICE_CLOCK_JUMP"
    PC_CLOCK_TAMPER = "PC_CLOCK_TAMPER"
    ZONE_PC_CLOCK_TAMPER = "ZONE_PC_CLOCK_TAMPER"
    DEVICE_LAN_BLIND_PERIOD = "DEVICE_LAN_BLIND_PERIOD"
    SERVICE_STOPPED = "SERVICE_STOPPED"
    ZONE_AGENT_UNEXPECTED_STOP = "ZONE_AGENT_UNEXPECTED_STOP"
    BACKFILL_SUSPICIOUS = "BACKFILL_SUSPICIOUS"


class IncidentSeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class PayloadType(StrEnum):
    ATTENDANCE = "ATTENDANCE"
    CLOCK_CHECK = "CLOCK_CHECK"
    OUTAGE = "OUTAGE"
    INCIDENT = "INCIDENT"
    HEARTBEAT = "HEARTBEAT"
