"""Durable manual attendance approval; automatic identity release is retired."""

from alembic import op
import sqlalchemy as sa

revision = "20260923_0035"
down_revision = "20260922_0034"
branch_labels = None
depends_on = None


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    tables = set(inspector.get_table_names())
    event_columns = {c["name"] for c in inspector.get_columns("add_attendance_events")}
    snapshot_columns = {c["name"] for c in inspector.get_columns("add_device_user_snapshots")}
    if "captured_cnic_lookup_hash" not in event_columns:
        op.add_column(
            "add_attendance_events", sa.Column("captured_cnic_lookup_hash", sa.String(64))
        )
    if "add_attendance_force_release_controls" not in tables:
        op.create_table(
            "add_attendance_force_release_controls",
            sa.Column("id", sa.Integer(), primary_key=True),
            sa.Column(
                "job_id",
                sa.Integer(),
                sa.ForeignKey("add_attendance_recovery_jobs.id"),
                nullable=False,
            ),
            sa.Column("request_key", sa.String(120), nullable=False),
            sa.Column("actor", sa.String(120), nullable=False),
            sa.Column("action", sa.String(20), nullable=False),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.UniqueConstraint("job_id", "request_key", name="uq_add_force_control_request"),
        )
    if "connector_boot_id" not in snapshot_columns:
        op.add_column(
            "add_device_user_snapshots",
            sa.Column("connector_boot_id", sa.String(100), nullable=True),
        )
    if "manual_release_required" not in event_columns:
        op.add_column(
            "add_attendance_events",
            sa.Column(
                "manual_release_required", sa.Boolean(), nullable=False, server_default=sa.false()
            ),
        )
    if "manual_release_required" not in event_columns:
        op.create_index(
            "ix_add_attendance_events_manual_release_required",
            "add_attendance_events",
            ["manual_release_required"],
        )
    # ### commands auto generated by Alembic - please adjust! ###
    if "add_attendance_force_release_tasks" not in tables:
        op.create_table(
            "add_attendance_force_release_tasks",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("job_id", sa.Integer(), nullable=False),
            sa.Column("connector_id", sa.Integer(), nullable=False),
            sa.Column("terminal_serial", sa.String(length=120), nullable=True),
            sa.Column("hardware_id", sa.String(length=120), nullable=False),
            sa.Column("high_water_id", sa.Integer(), nullable=False),
            sa.Column("cursor", sa.Integer(), nullable=False),
            sa.Column("user_cursor", sa.Integer(), nullable=False),
            sa.Column("baseline_revision", sa.Integer(), nullable=False),
            sa.Column("sync_revision", sa.Integer(), nullable=False),
            sa.Column("sync_round", sa.Integer(), nullable=False),
            sa.Column("sync_command_id", sa.Integer(), nullable=True),
            sa.Column("sync_boot_id", sa.String(length=100), nullable=True),
            sa.Column("sync_requested_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("sync_deadline", sa.DateTime(timezone=True), nullable=True),
            sa.Column("snapshot_id", sa.Integer(), nullable=True),
            sa.Column("synced_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("status", sa.String(length=30), nullable=False),
            sa.Column("checked_count", sa.Integer(), nullable=False),
            sa.Column("evidence_digest", sa.String(length=64), nullable=False),
            sa.Column("error_code", sa.String(length=80), nullable=True),
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["connector_id"],
                ["add_connectors.id"],
            ),
            sa.ForeignKeyConstraint(
                ["job_id"],
                ["add_attendance_recovery_jobs.id"],
            ),
            sa.ForeignKeyConstraint(
                ["snapshot_id"],
                ["add_device_user_snapshots.id"],
            ),
            sa.ForeignKeyConstraint(
                ["sync_command_id"],
                ["add_device_commands.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("job_id", "connector_id", name="uq_add_force_task_device"),
        )
    if "add_attendance_force_release_tasks" not in tables:
        op.create_index(
            op.f("ix_add_attendance_force_release_tasks_connector_id"),
            "add_attendance_force_release_tasks",
            ["connector_id"],
            unique=False,
        )
    if "add_attendance_force_release_tasks" not in tables:
        op.create_index(
            op.f("ix_add_attendance_force_release_tasks_job_id"),
            "add_attendance_force_release_tasks",
            ["job_id"],
            unique=False,
        )
    if "add_attendance_force_release_tasks" not in tables:
        op.create_index(
            "ix_add_force_task_schedule",
            "add_attendance_force_release_tasks",
            ["status", "updated_at"],
            unique=False,
        )
    if "add_attendance_force_release_users" not in tables:
        op.create_table(
            "add_attendance_force_release_users",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("task_id", sa.Integer(), nullable=False),
            sa.Column("device_user_id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.String(length=100), nullable=False),
            sa.Column("uid", sa.String(length=40), nullable=False),
            sa.Column("cnic_hash", sa.String(length=64), nullable=True),
            sa.Column("identity_fingerprint", sa.String(length=64), nullable=True),
            sa.ForeignKeyConstraint(
                ["device_user_id"],
                ["add_device_users.id"],
            ),
            sa.ForeignKeyConstraint(
                ["task_id"],
                ["add_attendance_force_release_tasks.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("task_id", "device_user_id", name="uq_add_force_baseline_user"),
        )
    if "add_attendance_force_release_users" not in tables:
        op.create_index(
            "ix_add_force_baseline_identity",
            "add_attendance_force_release_users",
            ["task_id", "user_id", "uid"],
            unique=False,
        )
    if "add_attendance_force_release_decisions" not in tables:
        op.create_table(
            "add_attendance_force_release_decisions",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("item_id", sa.Integer(), nullable=False),
            sa.Column("attendance_event_id", sa.Integer(), nullable=False),
            sa.Column("job_id", sa.Integer(), nullable=False),
            sa.Column("actor", sa.String(length=120), nullable=False),
            sa.Column("reason_encrypted", sa.Text(), nullable=False),
            sa.Column("proof", sa.JSON(), nullable=False),
            sa.Column("prior_state_encrypted", sa.Text(), nullable=False),
            sa.Column("payload_encrypted", sa.Text(), nullable=False),
            sa.Column("payload_digest", sa.String(length=64), nullable=False),
            sa.Column("operation_id", sa.String(length=36), nullable=False),
            sa.Column("audit_id", sa.Integer(), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            sa.ForeignKeyConstraint(
                ["attendance_event_id"],
                ["add_attendance_events.id"],
            ),
            sa.ForeignKeyConstraint(
                ["audit_id"],
                ["add_audit_events.id"],
            ),
            sa.ForeignKeyConstraint(
                ["item_id"],
                ["add_attendance_recovery_items.id"],
            ),
            sa.ForeignKeyConstraint(
                ["job_id"],
                ["add_attendance_recovery_jobs.id"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("operation_id"),
        )
    if "add_attendance_force_release_decisions" not in tables:
        op.create_index(
            op.f("ix_add_attendance_force_release_decisions_attendance_event_id"),
            "add_attendance_force_release_decisions",
            ["attendance_event_id"],
            unique=False,
        )
    if "add_attendance_force_release_decisions" not in tables:
        op.create_index(
            op.f("ix_add_attendance_force_release_decisions_item_id"),
            "add_attendance_force_release_decisions",
            ["item_id"],
            unique=True,
        )
    if "add_attendance_force_release_decisions" not in tables:
        op.create_index(
            op.f("ix_add_attendance_force_release_decisions_job_id"),
            "add_attendance_force_release_decisions",
            ["job_id"],
            unique=False,
        )
    if "add_attendance_force_release_scheduler" not in tables:
        op.create_table(
            "add_attendance_force_release_scheduler",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("id"),
        )
    # ### end Alembic commands ###
    op.execute(
        "INSERT INTO add_attendance_force_release_scheduler (id) VALUES (1) ON CONFLICT (id) DO NOTHING"
    )
    op.execute(
        "UPDATE add_attendance_events SET manual_release_required = true WHERE ords_status IN ('BLOCKED_IDENTITY', 'WAITING_FOR_SNAPSHOT', 'QUARANTINED_IDENTITY_REUSE')"
    )
    # Old firmware-receipt states can mask an unresolved identity hold. An old
    # automatic decision is not an administrator's approval under this policy.
    op.execute("""
        UPDATE add_attendance_events SET manual_release_required = true
        WHERE ords_status NOT IN ('ACKED','ACKED_CHECK') AND (
          identity_resolution_status IN ('BLOCKED_PROVENANCE','BLOCKED_IDENTITY','WAITING_FOR_SNAPSHOT','QUARANTINED_REUSE')
          OR EXISTS (SELECT 1 FROM add_attendance_safe_repair_decisions d
                     WHERE d.attendance_event_id = add_attendance_events.id AND d.actor LIKE 'system:%'))
    """)
    op.execute("""
        UPDATE add_attendance_events SET ords_status = 'BLOCKED_IDENTITY',
          oracle_confirmed_at = NULL, oracle_confirmation_path = NULL
        WHERE manual_release_required AND ords_status IN (
          'PENDING','IN_FLIGHT','FAILED_RETRYABLE','RETRYING','ACKED_FIRMWARE',
          'FIRMWARE_RECEIPT_UNVERIFIED','FIRMWARE_RECEIPT_VERIFYING')
          AND NOT EXISTS (SELECT 1 FROM add_attendance_safe_repair_decisions d
            WHERE d.attendance_event_id = add_attendance_events.id AND d.actor NOT LIKE 'system:%')
          AND NOT EXISTS (SELECT 1 FROM add_attendance_repair_items i
            JOIN add_attendance_repair_jobs j ON j.id = i.job_id
            WHERE i.attendance_event_id = add_attendance_events.id AND j.approved_at IS NOT NULL)
    """)
    op.execute("""
        UPDATE add_ords_outbox SET status = 'BLOCKED_IDENTITY', next_attempt_at = NULL,
          acknowledged_at = NULL, last_error = 'MANUAL_APPROVAL_REQUIRED'
        WHERE attendance_event_id IN (SELECT id FROM add_attendance_events
          WHERE manual_release_required AND ords_status = 'BLOCKED_IDENTITY')
    """)
    op.execute(
        "UPDATE add_attendance_recovery_jobs SET status = 'EXPIRED' WHERE action = 'SAFE_REPAIR' AND status IN ('CHECKING', 'CHECKED')"
    )
    op.execute(
        "UPDATE add_attendance_repair_jobs SET status = 'CANCELLED', cancellation_requested = true, error_code = 'POLICY_RETIRED', error_message = 'Use the manual Force release workflow.' WHERE approved_at IS NULL AND status NOT IN ('COMPLETED','COMPLETED_WITH_ATTENTION','CANCELLED')"
    )

    if op.get_bind().dialect.name == "postgresql":
        install_delivery_guards()


def install_delivery_guards() -> None:
    # A deferred database boundary validates the full committed approval and
    # receipt transaction and remains effective after application rollback.
    op.execute("""
        CREATE FUNCTION add_retain_manual_attendance_hold() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          IF NEW.ords_status IN ('BLOCKED_IDENTITY','WAITING_FOR_SNAPSHOT','QUARANTINED_IDENTITY_REUSE')
             OR (TG_OP = 'UPDATE' AND OLD.manual_release_required) THEN
            NEW.manual_release_required := true;
          END IF;
          RETURN NEW;
        END $$;
        CREATE TRIGGER add_retain_manual_attendance_hold BEFORE INSERT OR UPDATE ON add_attendance_events
          FOR EACH ROW EXECUTE FUNCTION add_retain_manual_attendance_hold();
        CREATE FUNCTION add_check_manual_attendance_delivery() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE event_id integer; attendance add_attendance_events%ROWTYPE;
          decision add_attendance_force_release_decisions%ROWTYPE; delivery_status text;
        BEGIN
          IF TG_TABLE_NAME = 'add_ords_outbox' THEN
            event_id := NEW.attendance_event_id;
            SELECT status INTO delivery_status FROM add_ords_outbox WHERE id = NEW.id;
          ELSE
            event_id := NEW.id;
            SELECT ords_status INTO delivery_status FROM add_attendance_events WHERE id = NEW.id;
          END IF;
          SELECT * INTO attendance FROM add_attendance_events WHERE id = event_id;
          IF NOT FOUND OR NOT attendance.manual_release_required
             OR delivery_status NOT IN ('PENDING','IN_FLIGHT','FAILED_RETRYABLE','RETRYING','ACKED','ACKED_CHECK') THEN
            RETURN NULL;
          END IF;
          SELECT * INTO decision FROM add_attendance_force_release_decisions
            WHERE attendance_event_id = event_id ORDER BY id DESC LIMIT 1;
          IF FOUND THEN
            IF delivery_status IN ('ACKED','ACKED_CHECK') AND NOT EXISTS (
              SELECT 1 FROM add_attendance_recovery_items i WHERE i.id = decision.item_id
                AND i.result ->> 'oracle_verified_payload_digest' = decision.payload_digest
                AND i.result ->> 'oracle_content_token' IS NOT NULL) THEN
              RAISE EXCEPTION 'Manual attendance requires matching Oracle content verification';
            END IF;
          ELSIF NOT EXISTS (SELECT 1 FROM add_attendance_safe_repair_decisions
              WHERE attendance_event_id = event_id AND actor NOT LIKE 'system:%')
            AND NOT EXISTS (SELECT 1 FROM add_attendance_repair_items i
              JOIN add_attendance_repair_jobs j ON j.id = i.job_id
              WHERE i.attendance_event_id = event_id AND j.approved_at IS NOT NULL) THEN
            RAISE EXCEPTION 'Attendance requires explicit administrator approval';
          END IF;
          RETURN NULL;
        END $$;
        CREATE CONSTRAINT TRIGGER add_manual_event_delivery_guard AFTER INSERT OR UPDATE ON add_attendance_events
          DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION add_check_manual_attendance_delivery();
        CREATE CONSTRAINT TRIGGER add_manual_outbox_delivery_guard AFTER INSERT OR UPDATE ON add_ords_outbox
          DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION add_check_manual_attendance_delivery();
        """)


def downgrade() -> None:
    # Keep approvals, pending deliveries and audit evidence on application rollback.
    pass
